apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: vault:1.0.3
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8200
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: http
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: http
            periodSeconds: 5
